Repository KOMARAUDAYKIRAN/E-commerce-AgriGro-Website-Project, pull requests merged in 2025-09, with the labels that each got.

#101 Added frontend and backend for auction system
  agriBazaar-backend/pom.xml
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/AgriBazaarBackendApplication.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/AuthUtil.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/SecurityConfig.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/WebConfig.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/controllers/AuctionController.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/controllers/AuthController.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/dto/LoginRequestDto.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/dto/LoginResponseDto.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/Auction.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/Bid.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/Product.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/User.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/repositories/AuctionRepository.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/repositories/BidRepository.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/repositories/UserRepository.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/AuctionSchedulerService.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/AuctionService.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/AuthService.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/BidService.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/ProductService.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/UserService.java
  agriBazaar-backend/src/main/resources/application.properties
  agriBazaar-backend/src/main/resources/data.sql
  agriBazaar-backend/src/main/resources/logback-spring.xml
  agriBazzar-frontend/auction.html
  agriBazzar-frontend/landing.html
  agriBazzar-frontend/login.html
  agriBazzar-frontend/won.html
Labels: GSSOC, Level 3

#100 Fix: merged navigation bars and added scroll-to-top button functionality
  agriBazzar-frontend/index.html
Labels: GSSOC, Level 3

#85 fix: reinstall react-scripts and patch vulnerabilities via dependency…
  admin-dashboard/package-lock.json
  admin-dashboard/package.json
Labels: enhancement, GSSOC, Level 2

#107 Updated backend for preorder system
  agriBazaar-backend/pom.xml
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/AuthUtil.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/JwtAuthenticationFilter.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/ReminderScheduler.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/SecurityConfig.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/config/WebConfig.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/controllers/PreOrderController.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/controllers/ProductController.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/PreOrder.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/entities/Product.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/repositories/PreOrderRepository.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/EmailServices.java
  agriBazaar-backend/src/main/java/com/agriBazaar/backend/services/PreOrderService.java
  agriBazaar-backend/src/main/resources/application.properties
  agriBazzar-frontend/Preorder.html
  agriBazzar-frontend/landing.html
  agriBazzar-frontend/login.html
Labels: help wanted, GSSOC, Level 3
